### ISSUE TITLE
Software updates available not being refreshed on Uyuni web UI

### ISSUE THREAD

**Issue by phibid** [uyuni-project/uyuni#1938]
Hi,

After a fresh install of the last stable Uyuni server version 2020.01, I have made some tests registering various clients OS with Salt method following the Uyuni documentation.

In the case of at least CentOS 8 and OpenSuse 15.1, once the servers are registered into Uyuni, I can see the list of available updates in the Web UI. However, after having patched them, the list of available updates does not disappear on the web UI, meanwhile that on the client, apt or zypper confirm that no more updates are available.

```
| System   | Updates | Patches | Packages | Configs | Base Channel                | System Type
| space02client |    | 253     | 330      | 0       | openSUSE Leap 15.1 (x86_64) | Salt
| space05client |    | 0       | 238      | 0       | CentOS 8 (x86_64)           | Salt
```
And after more than 24h, the state on the Web UI does not change. Am I missing something ?

Steps to reproduce:

1 - Install Stable Uyuni server following the documentation (https://www.uyuni-project.org/pages/stable-version.html)
2 - With spacewalk-common-channels create the Opensuse and CentOS 8 repos and sync them
3 - Create the activation key proper to each Channel
4 - Create the bootstrap script from the Web UI (Bootstrap using Salt)
5 - Create the bootstrap channels with mgr-create-bootstrap-repo
6 - Execute the bootstrap script on the clients specifying those values:

```
ACTIVATION_KEYS=1-centos8
ORG_GPG_KEY=uyuni-gpg-pubkey-0d20833e.key
```

(My first attempt for CentOS 8 failed because of those missing dependencies :python3-chardet, python3-urllib3, python3-pytz. Will open another issue regarding this)

7 - Accept the Salt key
8 - Wait to have the Web UI refreshed with the available updates
9 - Update the clients with "yum update" or "zypper up" depending of the OS

Thanks !

**Comment by paususe** [comment]
This is expected and there's work in progress to fix it (there are several PRs open). It should be fixed in the next release of Uyuni in a few weeks.

**Comment by phibid** [comment]
Thanks for the info. To which PRs are you referring to ? I could not find them.

**Comment by paususe** [comment]
> Thanks for the info. To which PRs are you referring to ? I could not find them.

https://github.com/uyuni-project/uyuni/pull/1868 (merged)
https://github.com/uyuni-project/uyuni/pull/1769 (merged)
https://github.com/uyuni-project/uyuni/pull/1974 (in progress)

and one more that is not yet created because code is still under development.

**Comment by paususe** [comment]
Does this still happen with 2020.05?

**Comment by phibid** [comment]
Yes it is.

I have updated a Debian 10 5h ago (apt upgrade), and the 14 updates still appear on the Uyuni Web console.


Philippe Bidault | Unix Engineer

Getronics
________________________________
M. 34617301667 | E. Philippe.Bidault@Getronics.com | W. www.getronics.com

Getronics CMC Service Desk Iberia S.L -  VAT No:S.L.: B66686262.
Registered Office - Getronics CMC Service Desk Iberia S.L, C/Rosselloi, Porcel, 21 planta 11, 08016 Barcelona, Spain.

The information transmitted is intended only for use by the addressee and may contain confidential and/or privileged material. Any review, re-transmission, dissemination or other use of it, or the taking of any action in reliance upon this information by persons and/or entities other than the intended recipient is prohibited. If you received this in error, please inform the sender and/or addressee immediately and delete the material.  Thank you.
Legal disclaimer: http://www.getronics.com/legal/

**Comment by paususe** [comment]
On .deb operating systems, this is unfortunately expected since we do have `zyppnotify` and `yumnotify` but there is no `debnotify` notifier beacon yet. Writing one is in our backlog.

**Comment by Shirocco88** [comment]
@paususe 
Could you please add label "ubuntu", "Debian" and "CentOS"

Thanks in Advance.

**Comment by paususe** [comment]
> @paususe
> Could you please add label "ubuntu", "Debian" and "CentOS"
> 
> Thanks in Advance.

done

**Comment by paususe** [comment]
What we are missing here is a .deb notifier, like yumnotify and zyppnotify

Here's an example of an apt hook:
https://salsa.debian.org/debian/how-can-i-help/-/tree/master

From looking at that hook, and at what our yumnotify and zyppnotify do, it seems writing an aptnotify should be rather simple.

More details here:
https://askubuntu.com/questions/869219/how-can-i-run-a-script-after-a-specific-package-is-upgraded

**Comment by phibid** [comment]
> 
> 
> On .deb operating systems, this is unfortunately expected since we do have `zyppnotify` and `yumnotify` but there is no `debnotify` notifier beacon yet. Writing one is in our backlog.
> 
> Could you please try if this still happens on openSUSE or CentOS, as you originally reported? I think the .deb case is covered by #1962

I can still observe the issue on CentOS 7 ssh-push registered clients.  If I take the CentOS 7 server `my_centos7_server`, those logs regularly appears (at least once a day) on the taskomatic logs:

```
2021-01-31 17:45:00,290 [Thread-4791] INFO  com.redhat.rhn.taskomatic.task.SSHPush - Executing actions for minion: my_centos7_server
2021-01-31 17:45:00,290 [Thread-4791] INFO  com.redhat.rhn.taskomatic.task.SSHPush - Performing a check-in for: my_centos7_server
```

However patch status is not refreshed on the GUI, so I guess that it is only executing a test.ping salt command, but not seems to execute a package refresh.

**Comment by Shirocco88** [comment]
there is an new PR: update to pkgset.py and MinionGeneralPillarGenerator.java:
#3645 Automatic cookie file selection in pkgset beacon

**Comment by phibid** [comment]
Seems that some improvements have been implemented, however, I can't see any difference until now on our prod platform (2021.06). 

All our registered clients use salt 'Push via SSH' contact method. If I update an Ubuntu 20.04 or a CentOS 7, the update numbers are not reflected in the GUI.

The call of `system_schedulepackagerefresh` API method through spacecmd is the only efficient way which allow me to have an uptodate GUI interface.

**Comment by Shirocco88** [comment]
@phibid : you need 2 files on your Ubuntu-20.04 uyuni-clients:
- The 99dpkgnotify file must be installed in /etc/apt/apt.conf.d/99dpkgnotify
- The dpkgnotify file must be installed in /usr/bin/dpkgnotify

see also:
https://github.com/openSUSE/salt/pull/347/files#diff-678fdbac1c14929f1fa4edf22fbf2bc0de15a9552c080b382c52dfd675d210ea

**Comment by rjmateus** [comment]
@phibid @Shirocco88 If ubuntu system was already registered to uyuni you should run a reactivation[0] to make sure files are copied and the needed beacon is written to the minion pillar data.

If you want you can also try to add the beacon information to the minion pillar, but I would not advise you.

[0] https://www.uyuni-project.org/uyuni-docs/en/uyuni/client-configuration/activation-keys.html#_combining_multiple_activation_keys

**Comment by phibid** [comment]
I can't see those files on a newly registered Ubuntu server 20.04. And same behaviour for the CentOS servers actually.
What do I miss here ?

**Comment by phibid** [comment]
I have copied both files by hand on the test server and tried to `apt upgrade`, however not really working as the dpkgnotify script is expected directory `/var/cache/salt/minion/dpkg.cookie` to exist which is not the case:

```
Traceback (most recent call last):
  File "/usr/bin/dpkgnotify", line 44, in <module>
    dpkg_post_invoke()
  File "/usr/bin/dpkgnotify", line 39, in dpkg_post_invoke
    with open(CK_PATH, 'w') as ck_fh:
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/minion/dpkg.cookie'
E: Problem executing scripts DPkg::Post-Invoke '/usr/bin/dpkgnotify'
E: Sub-process returned an error code
```

Is this really prepared to work for push via SSH Salt clients ?

**Comment by rjmateus** [comment]
O think it should work with salt push ssh. Wich salt version are you installing? The one provided by opensuse? If the files doesn't exists, maybe you are installing the version provided by deb

**Comment by phibid** [comment]
I am not installing any Salt packages on the registered system as they are salt push ssh clients, the idea being to have agentless servers.

**Comment by vzhestkov** [comment]
```
Traceback (most recent call last):
  File "/usr/bin/dpkgnotify", line 44, in <module>
    dpkg_post_invoke()
  File "/usr/bin/dpkgnotify", line 39, in dpkg_post_invoke
    with open(CK_PATH, 'w') as ck_fh:
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/minion/dpkg.cookie'
E: Problem executing scripts DPkg::Post-Invoke '/usr/bin/dpkgnotify'
E: Sub-process returned an error code
```
This happens because there is no directory on the system `/var/cache/salt/minion/` as it has no salt-minion installed and `dpkgnotify` makes no sense for it, please remove these files.
But for the problem with not refreshed installed packages it's better to check the events for the system in `Events -> History` tab, if there failed `Package List Refresh` actions, check the details.
If no any helpful information there, try to push `Update Packages List` button on `Software -> Packages` tab.
The only possible way to see the debuggin information for salt-ssh systems is to enable `trace` logging for the `master` and restart `salt-api` service (it's not the mistake, not the salt-master).
For example by putting the following line to the file `/etc/salt/master.d/logging.conf `:
```
log_level_logfile: trace
```
Full output will of salt-ssh sessions will be saved to `/var/log/salt/api`, but please do not keep `salt-api` running for long time with this logging level, it could cause utilization all the available space on the FS as it's too verbose.

**Comment by phibid** [comment]
I have noticed those continuous messages in `/var/log/salt/api`:

```
2021-09-06 21:08:08,490 [salt.roster      :106 ][ERROR   ][2751] Can't access roster for backend flat: Roster file "susemanager-roster-4139697080870696111.tmp" not found
2021-09-06 21:12:00,110 [salt.roster      :106 ][ERROR   ][2751] Can't access roster for backend flat: Roster file "susemanager-roster-15109459753019085932.tmp" not found
2021-09-06 21:12:00,139 [salt.roster      :106 ][ERROR   ][2751] Can't access roster for backend flat: Roster file "susemanager-roster-15109459753019085932.tmp" not found
2021-09-06 21:12:13,395 [salt.roster      :106 ][ERROR   ][2751] Can't access roster for backend flat: Roster file "susemanager-roster-3272017934072289195.tmp" not found
2021-09-06 21:12:38,842 [salt.roster      :106 ][ERROR   ][2751] Can't access roster for backend flat: Roster file "susemanager-roster-10048778000813879936.tmp" not found
```

Any relation with the state not being refreshed in the GUI ?

Anyway, I have tried to set the `trace` level here:

```
uyuni:/var/log/salt # cat /etc/salt/master.d/salt-ssh-logging.conf
ssh_minion_opts:
    log_file: ../../../../../var/log/salt-ssh.log
    log_level: trace
uyuni:/var/log/salt # diff /etc/salt/master.d/salt-ssh-logging.conf_ori /etc/salt/master.d/salt-ssh-logging.conf
3c3
<     log_level: warning
---
>     log_level: trace
```

But can't see any addition logs for the moment.

**Comment by Shirocco88** [comment]
@phibid :  did you restart Uyuni-Services ?
"spacewalk-service restart"

**Comment by vzhestkov** [comment]
@phibid this change increasing verbose level on salt-ssh minion side. If you need to increase logging level for salt-api processing salt-ssh sessions, you need to set logging level for master. But the messages `2021-09-06 21:12:38,842 [salt.roster      :106 ][ERROR   ][2751] Can't access roster for backend flat: Roster file "susemanager-roster-10048778000813879936.tmp" not found` is the sympthoms of a bug which was fixed already in the latest Uyuni Stable

**Comment by phibid** [comment]
I will close this old bug. In my case, I am using `venv-salt-minion` and don't have this issue anymore.
