### ISSUE TITLE
Uyuni Bugreport - Uyuni 2022.01 - Create kickstarttree does not work with mirrorlists

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#4747]
# Additional Information
Always reproducible on LEAP.

As mirror lists are the default method when using `/usr/bin/spacewalk-common-channels` users should always hit this issue when wanting to create kickstarts.

## Version of Uyuni Server and Proxy (if used)
```
Name         : Uyuni-Server-release
Version      : 2022.01
Release      : 167.1.uyuni1
Architecture : x86_64
Size         : 1.4 k
Quelle       : Uyuni-Server-release-2022.01-167.1.uyuni1.src.rpm
Repository   : @System
Aus Paketque : @commandline
Summary      : Uyuni Server
```

## Details about issue
When using reposync to create a kickstartable tree, the .treeinfo files are not detected when giving a mirrorlink as repo source.
```
# /usr/bin/spacewalk-repo-sync --channel almalinux8-aarch64 --type yum --non-interactive --sync-kickstart
08:45:56 ======================================
08:45:56 | Channel: almalinux8-aarch64
08:45:56 ======================================
08:45:56 Sync of channel started.
Metadaten von Repository 'almalinux8-aarch64' abrufen ...........................................[fertig]
Cache für Repository 'almalinux8-aarch64' erzeugen ..............................................[fertig]
Alle Repositorys wurden aktualisiert.
08:45:59 
08:45:59   Importing comps file 2e9a9c62e32faf650866918e2a249b9e15911422acce891569932aef84dd8226-comps-BaseOS.aarch64.xml.
08:45:59   Renaming non-standard filename 2e9a9c62e32faf650866918e2a249b9e15911422acce891569932aef84dd8226-comps-BaseOS.aarch64.xml to comps.aarch64.xml.
08:45:59 *** NOTE: Importing comps file for the channel 'almalinux8-aarch64'. Previous comps will be discarded.
08:45:59 Repo URL: https://mirrors.almalinux.org/mirrorlist/8/baseos
08:45:59     Packages in repo:              1457
08:46:03     No new packages to sync.
08:46:03 
08:46:03   Patches in repo: 0.
08:46:04 
08:46:04   Importing kickstarts.
08:46:04 Trying treeinfo
08:46:04 Trying .treeinfo
08:46:04     Kickstartable tree not detected (no valid treeinfo file)
08:46:04 Sync completed.
08:46:04 Total time: 0:00:07
```
Reason `get_file` is using the url without resolving the mirrorlink to an actual url:
https://github.com/uyuni-project/uyuni/blob/d473e7865777f375592b28f4fd71eff95eb751e7/backend/satellite_tools/repo_plugins/yum_src.py#L1205

From a security perspective, it makes sense to not resolve mirror links. Otherwise rogue servers could be added to these links. Kickstart files are not verified whether they have been tempered with or not. So only allowing direct links (from trusted sources) would reduce risks on embedding bad payloads onto infrastructure wide OS builds...

**Comment by vzhestkov** [comment]
@sbluhm this issue is most probably was fixed with https://github.com/uyuni-project/uyuni/pull/5752
It's not released yet, but available in `master`.

**Comment by sbluhm** [comment]
Can you please assign the ticket to me? I would retest when time permits.

**Comment by vzhestkov** [comment]
@sbluhm did you have a chance to test it? I just realized that the fix is partially in `python3-urlgrabber` which is not yet delivered to Leap 15.4 as it goes there from SLE 15, so it's possible that the issue is still there due to this delay.

**Comment by sbluhm** [comment]
Not yet. Still trying to get the server up and running to show the pages. Sorry. Will compare with the urlgrabber master/suse version at that point. Thank you

**Comment by sbluhm** [comment]
@vzhestkov , I just verified with today's master (AlmaLinux 9 to be fair) and the issue persists. I made sure that I use the patched urlgrabber from OBS.

```#  /usr/bin/spacewalk-repo-sync --channel  almalinux9-x86_64  --type yum --non-interactive --sync-kickstart
21:52:52 ======================================
21:52:52 | Channel: almalinux9-x86_64
21:52:52 ======================================
21:52:52 Sync of channel started.
21:53:09 
21:53:09   Importing comps file 944d17156737e57054a0b425fcd38263438275c6f50c24e4766e1b43f256416a-comps.xml.
21:53:09   Renaming non-standard filename 944d17156737e57054a0b425fcd38263438275c6f50c24e4766e1b43f256416a-comps.xml to comps.xml.
21:53:09 *** NOTE: Importing comps file for the channel 'almalinux9-x86_64'. Previous comps will be discarded.
21:53:12 Repo URL: https://mirrors.almalinux.org/mirrorlist/9/baseos
21:53:12     Packages in repo:              1527
21:53:22     No new packages to sync.
21:53:22 
21:53:22   Patches in repo: 67.
21:53:22 Add Patch ALBA-2022:2056
21:53:22 Add Patch ALSA-2022:7323
21:53:22 Add Patch ALEA-2022:1985
21:53:22 Add Patch ALSA-2022:7318
21:53:22 Add Patch ALBA-2022:2112
21:53:23 Add Patch ALSA-2022:6838
21:53:23 Add Patch ALBA-2022:2147
21:53:23 Add Patch ALBA-2022:1987
21:53:23 Add Patch ALSA-2022:6224
21:53:23 Add Patch ALSA-2022:5242
21:53:23 Add Patch ALBA-2022:2087
21:53:23 Add Patch ALBA-2022:1032
21:53:23 Add Patch ALSA-2022:6608
21:53:23 Add Patch ALSA-2022:7314
21:53:23 Add Patch ALBA-2022:2077
21:53:23 Add Patch ALBA-2022:2045
21:53:23 Add Patch ALSA-2022:6610
21:53:23 Add Patch ALEA-2022:1998
21:53:23 Add Patch ALSA-2022:5252
21:53:23 Add Patch ALBA-2022:2076
21:53:23 Add Patch ALBA-2022:2059
21:53:23 Add Patch ALBA-2022:2055
21:53:23 Add Patch ALSA-2022:7185
21:53:23 Add Patch ALSA-2022:6003
21:53:23 Add Patch ALEA-2022:2012
21:53:24 Add Patch ALSA-2022:5249
21:53:24 Add Patch ALSA-2022:6157
21:53:24 Add Patch ALSA-2022:5244
21:53:24     No new patch to sync.
21:53:24 
21:53:24   Importing kickstarts.
21:53:24 Trying treeinfo
21:53:24 Trying .treeinfo
21:53:25     Kickstartable tree not detected (no valid treeinfo file)
21:53:25 Sync completed.
21:53:25 Total time: 0:00:31
```

**Comment by meaksh** [comment]
Thanks for the feedback @sbluhm! 

I've reproduced the issue and found what causes the problem for mirrorlist repos. Also identified the another problem on `download.opensuse.org` repos.

I'll produce a PR for this soon.

**Comment by sbluhm** [comment]
I tested this successfully. Thank you so much! I have been waiting for this since Spacewalk days!
