### ISSUE TITLE
Bugreport - Can't Install ReportDB - Ident authentication failed for user "pythia_susemanager"

### ISSUE THREAD

**Issue by securecyberdefense** [uyuni-project/uyuni#4941]
# Problem description

After running `/usr/lib/susemanager/bin/mgr-setup -s`, I get the following output: 

```
Asserting correct java version...
/var/spacewalk already exists. Leaving it untouched.
Filesystem type for /var/cache is ext4 - ok.
Open needed firewall ports...
Warning: ALREADY_ENABLED: suse-manager-server
success
Performing forced re-installation!
Shutting down spacewalk services...
Done.
Delete existing database...
Delete existing salt minion keys
CREATE ROLE
* Loading answer file: /root/spacewalk-answers.
** Database: Setting up database connection for PostgreSQL backend.
** Database: Populating database.
** Database: --clear-db option used.  Clearing database.
** Database: Shutting down spacewalk services that may be using DB.
** Database: Services stopped.  Clearing DB.
*** Progress: ###############################
* Configuring tomcat.
* Setting up users and groups.
* Performing initial configuration.
* Configuring apache SSL virtual host.
* Configuring jabberd.
* Creating SSL certificates.
** SSL: Generating CA certificate.
** SSL: Generating server certificate.
** Database: Setting up report database.
*** Progress: #
Could not install report database.
ERROR: spacewalk-setup failed
```

Checking the `install_db.log` file, I get the following (hostname removed for confidentiality).
```
> cat /var/log/rhn/install_db.log
psql: error: connection to server at "<hostname>" (127.0.0.1), port 5432 failed: FATAL:  Ident authentication failed for user "pythia_susemanager"
```

## Version of Uyuni Server and Proxy (if used)

```
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.02-171.1.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.02-171.1.uyuni1.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

## Details about the issue

Running in AWS, using this AMI: https://aws.amazon.com/marketplace/pp/prodview-wn2xje27ui45o
OpenSUSE LEAP 15.3

`/etc/os-release`
```
NAME="openSUSE Leap"
VERSION="15.3"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.3"
PRETTY_NAME="openSUSE Leap 15.3"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.3"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

I'm following the official documentation on your website https://www.uyuni-project.org/uyuni-docs/en/uyuni/installation-and-upgrade/install-uyuni.html

Please let me know if there is anything else I can provide for you. 

Thanks!

**Comment by Thorfin** [comment]
I fixed this by commenting out those section in /etc/rhn/rhn.conf

**Comment by securecyberdefense** [comment]
First, thank you for taking your time to reply! 

When I run `/usr/lib/susemanager/bin/mgr-setup -s`, it seems to rewrite this file. I've even commented out all lines in that script that might overwrite the rhn.conf file. Somehow it's still getting rewritten. It must be some other script that's being called from it, I would imagine. 

Thanks again!

**Comment by securecyberdefense** [comment]
So after digging through a lot of bash scripts, I think I've narrowed the issue down to two possible issues. Ident authentication is clearly not supposed to be used in this scenario. What I can't tell is which one of these two configurations is wrong: 

In `/usr/bin/uyuni-setup-reportdb`, `$STANDALONE` being set to `true` seems to cause the default authentication method to be set to `ident` if you are accessing the Postgres DB via some hostname other than localhost

```
if $STANDALONE; then
        sed -i 's/^\([^#].*\)$/### next line has been commented out by uyuni-setup-reportdb: ###\n##\1/ ' $PG_HBA
        pg_hba_set "local" "all" "all" "" "peer"
        pg_hba_set "host" "all" "all" "127.0.0.1/32" "ident"
        pg_hba_set "host" "all" "all" "::1/128" "ident"
fi
```

Possible issue 1: `$STANDALONE` should be `false`
Possible issue 2: The DB is supposed to be accessed via localhost rather than the hostname of the machine. 

I attempted the first solution and changed `STANDALONE` to `false` and made sure `/var/lib/pg_hba.conf` was setup with `scram-sha-256` auth for the default host access line: 

```
host    all     all     127.0.0.1/32    scram-sha-256
```

This seems to have fixed the error. However, I'm not sure what implications that has on the system, now that I've setup the reportdb without `STANDALONE` mode set to `true`. 

Could you tell me what implications this will have? I'm certainly able to rebuild the system, so no big deal.

**Comment by trueshanti** [comment]
> It seems the config was added to rhn.conf, but the DB Schema and the DB user do not appear to exist in postgres yet.

as soon as i comment those lines they ssem to be regenerated at service-restart 

somehow i have the issue that in rhn.conf there is a new password .. but trying to test the connection with that password via

`psql -h 127.0.0.1 -W -U pythia_susemanager reportdb`


fails .. even after setting the password anew
my access-setting should be fine:
```
host	reportdb	all	127.0.0.1/32	scram-sha-256
host	reportdb	all	::1/128	scram-sha-256
host	reportdb	all	0.0.0.0/0	scram-sha-256
host	reportdb	all	::/0	scram-sha-256
```

```
 ⚡ root@raven  /home/shanti  psql -h 127.0.0.1 -W -U pythia_susemanager reportdb
Password: 
psql: error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  Ident authentication failed for user "pythia_susemanager"
connection to server at "127.0.0.1", port 5432 failed: FATAL:  Ident authentication failed for user "pythia_susemanager"
 ✘⚡ root@raven  /home/shanti  /usr/sbin/spacewalk-startup-helper check-database
report_db_host = raven.mojo.cc
psql: error: connection to server at "raven.mojo.cc" (127.0.0.1), port 5432 failed: FATAL:  Ident authentication failed for user "pythia_susemanager"
connection to server at "raven.mojo.cc" (127.0.0.1), port 5432 failed: FATAL:  Ident authentication failed for user "pythia_susemanager"
Report Database version '' is not supported for SUSE Manager/Uyuni on openSUSE Leap 15.3. Perform database migration.
```

strange to me :-/

**Comment by trueshanti** [comment]
i also noticed that postgre's ~/.bash_profile is not parsed correctly so PGDATA wont be in env . but thats minor to less

**Comment by juliogonzalez** [comment]
@mcalmer can you have a quick look or assign to someome from your squad? Seems a problem with the reportdb setup?

**Comment by mcalmer** [comment]
Please use 2022.03. There were already a lot of improvements in the setup scripts. 
By default "STANDALONE" is not set or used. I think you want to setup on the same DB as the main uyuni DB.
If i remember correctly I also fixed something around the usage of "STANDALONE".

If possible try with the new version as the old really had some problms.

**Comment by securecyberdefense** [comment]
I appreciate the help guys. From what I can tell, my change has not affected the system. I don't have time in the budget to redeploy everything, unfortunately, so I won't be able to do that. As long as you think I haven't completely screwed anything there. 

On my end, I'm good, so don't feel the need to keep this open on my behalf, unless you need to track this as a bug. 

Thanks for the help, everyone! I appreciate your time and efforts.

**Comment by jameski83** [comment]
I am currently getting the same issue as above when trying to run `/usr/lib/susemanager/bin/mgr-setup -s`. The above `$STANDALONE` fix did not work for me. Please let me know if you need any more details.

```
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : uyuni-server-stable
Name           : Uyuni-Server-release
Version        : 2022.03-172.4.uyuni1
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : Level 3
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2022.03-172.4.uyuni1.src
Summary        : Uyuni Server
Description    :
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

**Comment by mcalmer** [comment]
@jameski83 cat you check what error message you see in /var/log/rhn/install_db.log?

**Comment by jameski83** [comment]
Hi - see below

```
cat /var/log/rhn/install_db.log
psql: error: connection to server at "uyuni.admin.lab" (::1), port 5432 failed: FATAL:  Ident authentication failed for user "pythia_susemanager"
```

**Comment by mcalmer** [comment]
In `/var/lib/pgsql/data/pg_hba.conf` you find these 2 lines:

```
host    all     all     127.0.0.1/32    ident
host    all     all     ::1/128 ident
```

Can you try to remove them or move all lines which have "all" as second value to the end of the file.
Restart postgresql and try again if the connection is now possible,

**Comment by jameski83** [comment]
Moved the entries to the end of the file as suggested and restarted postgresql and get the below error :

```
psql: error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  Ident authentication failed for user "pythia_susemanager"
connection to server at "127.0.0.1", port 5432 failed: FATAL:  Ident authentication failed for user "pythia_susemanager"
```

**Comment by mcalmer** [comment]
can you paste your pg_hba.conf here?

**Comment by mcalmer** [comment]
Would be interresting if the following pg_hba.conf would work for you:

```
local uyuni uyuni scram-sha-256
host uyuni uyuni 127.0.0.1/32 scram-sha-256
host uyuni uyuni ::1/128 scram-sha-256
local	reportdb	all	scram-sha-256
host	reportdb	all	127.0.0.1/32	scram-sha-256
host	reportdb	all	::1/128	scram-sha-256
host	reportdb	all	0.0.0.0/0	scram-sha-256
host	reportdb	all	::/0	scram-sha-256
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            ident
host    replication     all             ::1/128                 ident
# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            ident
# IPv6 local connections:
host    all             all             ::1/128                 ident
```

If not, please remove all lines which end with "ident".
Do not forget to restart postgresql after you changed the config.

**Comment by jameski83** [comment]
i've tried the above pg_hba.conf and also removed the ident lines but both times when I try to restart postgresql it fails to start

```
systemctl status postgresql.service
● postgresql.service - PostgreSQL database server
     Loaded: loaded (/usr/lib/systemd/system/postgresql.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Mon 2022-04-11 13:06:53 UTC; 4s ago
    Process: 4001 ExecStart=/usr/share/postgresql/postgresql-script start (code=exited, status=1/FAILURE)

Apr 11 13:06:53 uyuni systemd[1]: Starting PostgreSQL database server...
Apr 11 13:06:53 uyuni postgresql-script[4010]: 2022-04-11 13:06:53.604 UTC   [4010]LOG:  redirecting log output to logging collector process
Apr 11 13:06:53 uyuni postgresql-script[4010]: 2022-04-11 13:06:53.604 UTC   [4010]HINT:  Future log output will appear in directory "log".
Apr 11 13:06:53 uyuni postgresql-script[4008]: pg_ctl: could not start server
Apr 11 13:06:53 uyuni postgresql-script[4008]: Examine the log output.
Apr 11 13:06:53 uyuni systemd[1]: postgresql.service: Control process exited, code=exited, status=1/FAILURE
Apr 11 13:06:53 uyuni systemd[1]: postgresql.service: Failed with result 'exit-code'.
Apr 11 13:06:53 uyuni systemd[1]: Failed to start PostgreSQL database server.
```

current pg_hba.conf

```
local uyuni uyuni scram-sha-256
host uyuni uyuni 127.0.0.1/32 scram-sha-256
host uyuni uyuni ::1/128 scram-sha-256
local	reportdb	all	scram-sha-256
host	reportdb	all	127.0.0.1/32	scram-sha-256
host	reportdb	all	::1/128	scram-sha-256
host	reportdb	all	0.0.0.0/0	scram-sha-256
host	reportdb	all	::/0	scram-sha-256
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all
local   replication     all                                     peer
# "local" is for Unix domain socket connections only
local   all             all                                     peer
```

postgresql was started with the original config file.

**Comment by jameski83** [comment]
the logs said `[1991]CONTEXT:  line 11 of configuration file "/var/lib/pgsql/data/pg_hba.conf"` which was `local   replication     all`. I removed this line and the service started ok. 

Current pg_hba.conf

```
local uyuni uyuni scram-sha-256
host uyuni uyuni 127.0.0.1/32 scram-sha-256
host uyuni uyuni ::1/128 scram-sha-256
local	reportdb	all	scram-sha-256
host	reportdb	all	127.0.0.1/32	scram-sha-256
host	reportdb	all	::1/128	scram-sha-256
host	reportdb	all	0.0.0.0/0	scram-sha-256
host	reportdb	all	::/0	scram-sha-256
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     peer
# "local" is for Unix domain socket connections only
local   all             all                                     peer
```


Postgresql error

```
psql: error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "pythia_susemanager"
connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "pythia_susemanager"
```

**Comment by mcalmer** [comment]
Ok, sorry. The line `local   replication     all` really miss the 4th value. I think this was some copy and paste error from my side.

**Comment by mbussolotto** [comment]
@jameski83 Can you please try to add:

```
local	uyuni		postgres	peer
local	reportdb	postgres	peer
local	replication	postgres	peer
```
At the top of `/var/lib/pgsql/data/pg_hba.conf` , then postgres restart?  If you have still failure, we should find something interesting in log inside `/var/lib/pgsql/data/log/` . Thanks!

**Comment by jameski83** [comment]
@mbussolotto I've added the lines as requested at the top of `/var/lib/pgsql/data/pg_hba.conf` and re-ran `/usr/lib/susemanager/bin/mgr-setup -s` and it seemed to finish ok this time. The web ui loads up now.
