### ISSUE TITLE
Kickstart stopped working for RHEL9 related systems

### ISSUE THREAD

**Issue by sbluhm** [uyuni-project/uyuni#5513]
# Problem description

When using a RHEL9 related kickstart profile, the Autoinstallation feature does not seem to work anymore.

It seems that some "install" function has been removed.

## Version of Uyuni Server and Proxy (if used)

```dnf info Uyuni-Server-release
# dnf info Uyuni-Server-release
Letzte Prüfung auf abgelaufene Metadaten: vor 3:39:45 am Sa 28 Mai 2022 08:23:47 CEST.
Installierte Pakete
Name         : Uyuni-Server-release
Version      : 2022.01
Release      : 167.1.uyuni1
Architecture : x86_64
Size         : 1.4 k
Quelle       : Uyuni-Server-release-2022.01-167.1.uyuni1.src.rpm
Repository   : @System
Aus Paketque : @commandline
Summary      : Uyuni Server
Lizenz       : GPL-2.0-or-later
Description  : Uyuni lets you efficiently manage physical, virtual,
             : and cloud-based Linux systems. It provides automated and cost-effective
             : configuration and software management, asset management, and system
             : provisioning.

```
Although product has been updated to release 2022.05. guess it wasn't done properly.

## Details about the issue

Creation of kickstart profile:
1. Sync AlmaLinux 9 baseos/appstream. Tick "create kickstartable tree"
2. Select the Autoinstallation -> distribution to be Red Hat 8 (9 is not available) and verify the data.
3. Create a profile.
Do a network boot and select the new profile.
In addition to the screenshot below, similar errors about "install" being removed show up in the logs flying by.

![grafik](https://user-images.githubusercontent.com/1790211/170820551-a3a73388-ee7d-4ec0-94cf-281267dc7d66.png)

**Comment by sbluhm** [comment]
Strangely the kickstart file converter from RedHat does not flag any issues related to the error above:
https://access.redhat.com/labs/kickstartconvert/

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/performing_an_advanced_rhel_installation/index#deprecated-kickstart-comands-and-options_kickstart-changes
states:
> install - use the subcommands or methods directly as commands

Comparing it to the kickstart generator from RedHat, it seems only the install line is missing compared to the Uyuni generated one. So maybe only that one needs to be dropped.
(https://access.redhat.com/labs/kickstartconfig/)

**Comment by sbluhm** [comment]
ok, the "install" option can be deselected at `Autoinstallation`--> `Profiles` --> <profile> --> `Autoinstallation Details` --> `Advanced Options`.

Not sure if this needs to be removed or kept...

**Comment by aaannz** [comment]
The kssendmac error should be fixed as well. Do you know how backward compatible is to use inst.ks.sendmac ?

**Comment by sbluhm** [comment]
Admittedly, I ignored it as it didn't stop the installation. I also cannot find it in the kickstart file so I am not sure where this flag actually comes from.
RHEL7 supports `inst.ks.sendmac`. So if RHEL6 is not an issue it might just be adapted?

**Comment by sbluhm** [comment]
@cbosdo will do so by hopefully end of next week. Kickstart itself "always" worked if "install" has not been selected. Will update the thread after testing.

**Comment by sbluhm** [comment]
@cbosdo , I finally checked and I still get both issues (tested on Leap 15.4):
1. On the new RHEL9 profile, the install option is still available, selectable and functional.
2. On client boot, the install option is loaded and the installation fails. But this time earlier in the process. This is probably due to an adapted 9.1 boot process.
3. The same message of kssendmac is depreacted occurs (but again, installation continues).

I think only option 1 needs fixing as one can accidentally select the install option (or someone like me who doesn't know which options to use and which ones not to use for EL9).
Option 3 is not a showstopper. Not sure if there is any impact on other features though.

**Comment by sbluhm** [comment]
Can you reopen this issue? I strangely cannot. Thank you.

**Comment by cbosdo** [comment]
I won't have time to look into it these days.

**Comment by sbluhm** [comment]
I don't think this should have high priority unless some for me unknown features are impacted by inst.ks.sendmac.

What would be the closure criteria? Removal of the install option on the UI or fixing the inst.ks.sendmac or both? Maybe I can add it to my todo list at some point.

**Comment by cbosdo** [comment]
The only thing I can do is to disable the install option in the UI for EL9. The sendmac problem is fixed in upstream cobbler, just not shipped yet.

**Comment by sbluhm** [comment]
Verified working. Thank you.
