### ISSUE TITLE
Activation Keys Groups Tab broken after upgrade to 2024.12

### ISSUE THREAD

**Issue by fd-SR** [uyuni-project/uyuni#9754]
### Problem description

We have recently upgraded our Uyuni server from 2024.07 (already podman) to 2024.12.
So far everything seemed to work fine, but I stumbled across an issue with the group assignment on activation keys.
If I try to access the _Groups_ tab of an activation key an _Internal Server Error_ is shown.
The groups assignment itself still seems to work since for instance kickstarted systems still get the correct grouping assigned.
But it is not possible to edit groups on activation keys via the Web GUi. 
I also tried creating a new activation key and while at first it seems to work (the _Groups_ tab shows up fine including the subtabs _List/Leave_ and _Join_) the moment a group is assigned/joined to that new activation key, it shows the same _Internal Server Error_.

### Steps to reproduce

1. Try to access the _Groups_ tab on an activation key which has groups assigned.
2. Internal Server Error shows and WEB TRACEBACK error is logged
3.
...

### Uyuni version

```bash
Information for package Uyuni-Server-release:
---------------------------------------------
Repository     : @System
Name           : Uyuni-Server-release
Version        : 2024.12-241000.225.1.uyuni5
Arch           : x86_64
Vendor         : obs://build.opensuse.org/systemsmanagement:Uyuni
Support Level  : unknown
Installed Size : 1.4 KiB
Installed      : Yes (automatically)
Status         : up-to-date
Source package : Uyuni-Server-release-2024.12-241000.225.1.uyuni5.src
Upstream URL   : https://www.uyuni-project.org/
Summary        : Uyuni Server
Description    : 
    Uyuni lets you efficiently manage physical, virtual,
    and cloud-based Linux systems. It provides automated and cost-effective
    configuration and software management, asset management, and system
    provisioning.
```

### Uyuni proxy version (if used)

```bash

```

### Useful logs

```bash
The following exception occurred while executing this request:
GET /rhn/activationkeys/groups/List.do

Date:2/11/25 11:45:56 AM UTC
Headers:
  host: uyuni.redacted.url
  user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
  accept: */*
  accept-language: en-US,en;q=0.5
  accept-encoding: gzip, deflate, br
  X-PJAX: true
  X-Requested-With: XMLHttpRequest
  content-type: application/x-www-form-urlencoded
  connection: keep-alive
  referer: https://uyuni.redacted.url/rhn/activationkeys/Edit.do?tid=43
  cookie: JSESSIONID=E2F8216465E358CDB898949DDA1CCBB0; pxt-session-cookie=3914920xd759ef2330bf0f2f4092a5d4b8ba4e485e4c41f8651cf51470d566ace6f24ae1
  Sec-Fetch-Dest: empty
  Sec-Fetch-Mode: cors
  Sec-Fetch-Site: same-origin

Request:
Local Name = uyuni.redacted.url
Server Name = uyuni.redacted.url
Requested Session Id came from Cookie
Requested Session Valid = true
Session = org.apache.catalina.session.StandardSessionFacade@73857c9[session=StandardSession[E2F8216465E358CDB898949DDA1CCBB0]]
Protocol = https
Request Locale = en_US
Request Character Encoding = UTF-8
Attribute Names = rhnActiveLang, all, org.apache.struts.action.MESSAGE, org.apache.struts.action.mapping.instance, parentUrl, list_1154021400_rhn_set, org.apache.tomcat.util.net.secure_protocol_version, requestedUri, session, javax.servlet.request.key_size, org.apache.struts.action.MODULE, description, activationkey, javax.servlet.request.cipher_suite, javax.servlet.request.ssl_session_id, __sitemesh__filterapplied, accessMap, javax.servlet.jsp.jstl.fmt.timeZone.request, list_1154021400_selected_amt, 


User Information:
User uyuniadmin (id 1, org_id 1)

Exception:
javax.servlet.ServletException: javax.servlet.jsp.JspException: java.lang.UnsupportedOperationException
	at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:651)
	at org.apache.jsp.WEB_002dINF.pages.activationkeys.groups.list_jsp._jspService(Unknown Source)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:641)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:415)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:347)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:284)
	at org.apache.struts.action.RequestProcessor.doForward(RequestProcessor.java:1085)
	at org.apache.struts.action.RequestProcessor.processForwardConfig(RequestProcessor.java:398)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:241)
	at com.redhat.rhn.frontend.struts.RhnRequestProcessor.process(RhnRequestProcessor.java:103)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1196)
	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:414)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at com.redhat.rhn.frontend.servlets.AuthFilter.doFilter(AuthFilter.java:112)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:142)
	at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at com.redhat.rhn.frontend.servlets.LocalizedEnvironmentFilter.doFilter(LocalizedEnvironmentFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at com.redhat.rhn.frontend.servlets.EnvironmentFilter.doFilter(EnvironmentFilter.java:99)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at com.redhat.rhn.frontend.servlets.SessionFilter.doFilter(SessionFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at com.redhat.rhn.frontend.servlets.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:424)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:937)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.UnsupportedOperationException
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.sort(ImmutableCollections.java:261)
	at com.redhat.rhn.frontend.taglibs.list.DataSetManipulator.sort(DataSetManipulator.java:129)
	at com.redhat.rhn.frontend.taglibs.list.ListTag.doAfterBodyRenderListBegin(ListTag.java:755)
	at com.redhat.rhn.frontend.taglibs.list.ListTag.doAfterBody(ListTag.java:780)
	at org.apache.jsp.WEB_002dINF.pages.common.fragments.activationkeys.groups_jspf._jspx_meth_rl_005flist_005f0(Unknown Source)
	at org.apache.jsp.WEB_002dINF.pages.common.fragments.activationkeys.groups_jspf._jspx_meth_c_005fwhen_005f0(Unknown Source)
	at org.apache.jsp.WEB_002dINF.pages.common.fragments.activationkeys.groups_jspf._jspx_meth_c_005fchoose_005f0(Unknown Source)
	at org.apache.jsp.WEB_002dINF.pages.common.fragments.activationkeys.groups_jspf._jspx_meth_rl_005flistset_005f0(Unknown Source)
	at org.apache.jsp.WEB_002dINF.pages.common.fragments.activationkeys.groups_jspf._jspService(Unknown Source)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:641)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:517)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:460)
	at org.apache.taglibs.standard.tag.common.core.ImportSupport.acquireString(ImportSupport.java:301)
	at org.apache.taglibs.standard.tag.common.core.ImportSupport.doEndTag(ImportSupport.java:155)
	at org.apache.jsp.WEB_002dINF.pages.activationkeys.groups.list_jsp._jspx_meth_c_005fimport_005f0(Unknown Source)
	... 61 more
```

**Comment by agraul** [comment]
@fd-SR thank you for the report! I can reproduce it, once a group is assigned to an activation key, accessing `/rhn/activationkeys/group/List.do` causes an Internal Server Error.

**Comment by rjmateus** [comment]
@fd-SR thank you for the report, it's an issue that we are already looking at and was cause by some changes in java code we made a few week ago. 
@cbbayburt this look to be another instance of the errors you were looking at. Do you know if this particular one is already addressed?

**Comment by cbbayburt** [comment]
I have a patch to be merged for all the affected pages. You Van expect the fix in the next release.

**Comment by CDellaGiusta** [comment]
Duplicate of https://github.com/SUSE/spacewalk/issues/26534

**Comment by stdevel** [comment]
This is still present in the following container image:

```command
# podman images
REPOSITORY                                                                            TAG         IMAGE ID      CREATED        SIZE
registry.opensuse.org/systemsmanagement/uyuni/stable/patches/containers/uyuni/server  latest      c74ec9e87f04  3 weeks ago    1.95 GB
```

```command
# podman image inspect registry.opensuse.org/systemsmanagement/uyuni/stable/patches/containers/uyuni/server
[
     {
          "Id": "c74ec9e87f046a7454b1e1d50423cadd494a017cc26e4b7702cab8d50f2628de",
          "Digest": "sha256:a3654cf29e098bf272088deb9bbace1d1f052cc3b5f57b54bd663a3478891ece",
          "RepoTags": [
               "registry.opensuse.org/systemsmanagement/uyuni/stable/patches/containers/uyuni/server:latest"
          ],
          "RepoDigests": [
               "registry.opensuse.org/systemsmanagement/uyuni/stable/patches/containers/uyuni/server@sha256:a3654cf29e098bf272088deb9bbace1d1f052cc3b5f57b54bd663a3478891ece",
               "registry.opensuse.org/systemsmanagement/uyuni/stable/patches/containers/uyuni/server@sha256:bd4be608214bab531fe7c659c8d5707be8e4b7d36d840a1cf7c4d7951c78ec2f"
          ],
          "Parent": "",
          "Comment": "",
          "Created": "2025-04-17T16:14:54.721818819Z",
...
```

**Comment by stdevel** [comment]
Any news on this? I'm still having the same issue on SUSE Manager 5.0.4:

```command
# podman images
REPOSITORY                                                        TAG         IMAGE ID      CREATED        SIZE
registry.suse.com/suse/manager/5.0/x86_64/server                  5.0.4       69ec8c1b69d9  5 weeks ago    1.9 GB
registry.suse.com/suse/manager/5.0/x86_64/server-migration-14-16  5.0.4       55946596d13e  2 months ago   613 MB
```

```command
# podman image inspect registry.suse.com/suse/manager/5.0/x86_64/server:5.0.4 | less
[
     {
          "Id": "69ec8c1b69d96f7e92ffb76cac5874069a8b06b7762ee9bfe27f037cfb75bb7a",
          "Digest": "sha256:d6869b103ce0f0739986bed12525e42fa2d1450363a7037a1ce6eb8b05e70df5",
          "RepoTags": [
               "registry.suse.com/suse/manager/5.0/x86_64/server:5.0.4"
          ],
          "RepoDigests": [
               "registry.suse.com/suse/manager/5.0/x86_64/server@sha256:d6869b103ce0f0739986bed12525e42fa2d1450363a7037a1ce6eb8b05e70df5"
          ],
          "Parent": "",
          "Comment": "",
          "Created": "2025-05-09T09:29:45.866630281Z",
...
```

I also opened a SCC ticket **01584151** for this.

**Comment by RenownTwiz** [comment]
This seems to be fixed in Uyuni 2025.07.
